project:
  type: book
  output-dir: docs

book:
  title: "IC Engineering I"
  author: "Saroj Rout"
  date: "4/17/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - passives.qmd
    - circuits.qmd
    - FirstOrderCkts.qmd
    - devices.qmd
    - bjt.qmd
    - mos.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand



