project:
  type: book
  output-dir: docs

book:
  title: "IC Engineering I"
  author: "Saroj Rout"
  date: "1/8/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - passives.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



